import { NgModule } from '@angular/core';
import {  MatInputModule }  from '@angular/material/input';
//     MatAutocompleteModule,
//     MatButtonModule,
//     MatButtonToggleModule,
//     MatCardModule,
import { MatCheckboxModule } from '@angular/material/checkbox';
//     MatChipsModule,
//     MatDatepickerModule,
//     MatDialogModule,
//     MatExpansionModule,
//     MatGridListModule,
//     MatIconModule,
//     MatListModule,
//     MatMenuModule,
//     MatNativeDateModule,
//     MatPaginatorModule,
//     MatProgressBarModule,
//     MatProgressSpinnerModule,
//     MatRadioModule,
//     MatRippleModule,
import {MatSelectModule} from '@angular/material/select';
//     MatSidenavModule,
//     MatSliderModule,
//     MatSlideToggleModule,
//     MatSnackBarModule,
//     MatSortModule,
//     MatTableModule,
//     MatTabsModule,
import { MatToolbarModule } from '@angular/material/toolbar';
//     MatTooltipModule,
//     MatStepperModule,


@NgModule({
  imports: [
       MatInputModule,
//         MatAutocompleteModule,
//         MatButtonModule,
//         MatButtonToggleModule,
//         MatCardModule,
         MatCheckboxModule,
//         MatChipsModule,
//         MatDatepickerModule,
//         MatDialogModule,
//         MatExpansionModule,
//         MatGridListModule,
//         MatIconModule,*/         
//         MatListModule,
//         MatMenuModule,
//         MatNativeDateModule,
//         MatPaginatorModule,
//         MatProgressBarModule,
//         MatProgressSpinnerModule,
//         MatRadioModule,
//         MatRippleModule,
         MatSelectModule,
//         MatSidenavModule,
//         MatSliderModule,
//         MatSlideToggleModule,
//         MatSnackBarModule,
//         MatSortModule,
//         MatTableModule,
//         MatTabsModule,
         MatToolbarModule,
//         MatTooltipModule,
//         MatStepperModule,
  ],
  exports: [
    MatInputModule,
//         MatAutocompleteModule,
//         MatButtonModule,
//         MatButtonToggleModule,
//         MatCardModule,
         MatCheckboxModule,
//         MatChipsModule,
//         MatDatepickerModule,
//         MatDialogModule,
//         MatExpansionModule,
//         MatGridListModule,
//         MatIconModule,
//         MatListModule,
//         MatMenuModule,
//         MatNativeDateModule,
//         MatPaginatorModule,
//         MatProgressBarModule,
//         MatProgressSpinnerModule,
//         MatRadioModule,
//         MatRippleModule,
         MatSelectModule,
//         MatSidenavModule,
//         MatSliderModule,
//         MatSlideToggleModule,
//         MatSnackBarModule,
//         MatSortModule,
//         MatTableModule,
//         MatTabsModule,
         MatToolbarModule,
//         MatTooltipModule,
//         MatStepperModule,
  ]
})

export class MaterialModule { }
